---

- name: generate | key INFO
  debug:
    msg: "Generating a key for user '{{ record['user'] }}' with e-mail '{{ record['email'] }}'"

# https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html
- name: generate | key
  shell: echo "{{ lookup('template', 'generate/key.j2') }}" | gpg --batch --generate-key -   # noqa 301, 306
  changed_when: false     # TODO: idempotence fails
  no_log: "{{ hide_secrets }}"

- name: generate | sub-keys INFO
  when: record['sub_keys'] is defined
  block:
    - name: generate | find sub-key fingerprint
      shell: "gpg --fingerprint {{ record['email'] }} | sed -n 2p | tr -d ' '"   # noqa 306
      changed_when: false
      register: find_fingerprint

    - name: generate | sub-key fingerprint
      set_fact:
        fingerprint: "{{ find_fingerprint.stdout }}"

    - name: generate | sub-key notification
      debug:
        msg: "Generating sub-keys for user '{{ record['user'] }}' with e-mail '{{ record['email'] }}' [fpr: {{ fingerprint }}]"

    - name: generate | sub-keys
      shell: >-
        echo "{{ record['passphrase'] }}"
        | {{ gpg_command }} --quick-add-key {{ fingerprint }} {{ lookup('template', './generate/subkey.j2') | trim }}     # noqa 306
      changed_when: false     # TODO: idempotence fails
      loop: "{{ record['sub_keys'] }}"
      loop_control:
        loop_var: subkey
      vars:
        gpg_command: "gpg --batch --pinentry-mode loopback --passphrase-fd 0"
      no_log: "{{ hide_secrets }}"
