---

- name: generate | keys
  when:
    - gpg_generate['keys'] is defined
    - gpg_generate['keys'] | length > 0
  include_tasks: key.yml
  loop: "{{ gpg_generate['keys'] }}"
  loop_control:
    loop_var: record
  no_log: "{{ hide_secrets }}"
