---

- name: generate keys 
  when:
    - keys is defined
    - keys | length > 0
  include_tasks: generate/key.yml
  loop: "{{ keys }}"
  loop_control:
    loop_var: record 
  no_log: "{{ hide_secrets }}"

