---

- name: generate | keys
  when:
    - generate['keys'] is defined
    - generate['keys'] | length > 0
  include_tasks: key.yml
  loop: "{{ generate['keys'] }}"
  loop_control:
    loop_var: record
  no_log: "{{ hide_secrets }}"
