---

- name: harden | identify fingerprint
  shell: >-
    gpg --list-secret-keys --with-colons --fingerprint {{ key['email'] }}
    | sed -n 's/^fpr:::::::::\([[:alnum:]]\+\):/\1/p' | sed -n 1p    # noqa 306
  changed_when: false
  register: fp

- name: harden | keys
  vars:
    gpg_command: "gpg --pinentry-mode loopback --batch --yes --passphrase-fd 0"
  block:
    - name: remove private master key
      shell: echo "{{ key['passphrase'] }}" | {{ gpg_command }} --delete-secret-key {{ fp.stdout }}   # noqa 306

    - name: reimport only private subkeys
      shell: echo "{{ key['passphrase'] }}" | {{ gpg_command }} --import {{ key['email'] }}/{{ key['email'] }}.private.subkeys_only.gpg-key   # noqa 306
      args:
        chdir: "{{ export_dir }}"
      no_log: "{{ hide_secrets }}"
