---

- name: establish dependencies
  package:
    name:
      - gpg
      - gpg-agent
    state: present
  tags: install

- name: generate GPG keys
  when: generate is defined
  include_tasks: generate/main.yml
  tags: configure

- name: export GPG keys
  when:
    - gpg_export is defined
    - gpg_export['dir'] is defined
  block:
    - include_tasks: export/main.yml
      tags: configure

    - name: harden local version of exported private keys
      include_tasks: harden.yml
      vars:
        export_dir: "{{ gpg_export['dir'] }}"
      loop: "{{ gpg_export['keys'] }}"
      loop_control:
        loop_var: key
      tags: configure

- name: import GPG keys
  when: gpg_import is defined
  include_tasks: import/main.yml
  tags: configure
