---

- name: ensure export directory presence
  file:
    path: "{{ export_dir }}/{{ email }}"
    state: directory

- name: generate revocation certificate
  shell: echo -e "y\n0\n\ny" > "{{ command_file }}" && echo "{{ passphrase }}" | gpg --pinentry-mode loopback --command-file "{{ command_file }}" --passphrase-fd 0 --gen-revoke "{{ email }}" > '<{{ email }}>.revocation-certificate'
  args:
    chdir: "{{ export_dir }}/{{ email }}"
    executable: bash
  vars:
    command_file: /tmp/cmd

- name: export public key
  shell: echo "{{ passphrase }}" | gpg --pinentry-mode loopback --batch --yes --passphrase-fd 0 --export --armor "{{ email }}" > '<{{ email }}>.public.gpg-key'
  args:
    chdir: "{{ export_dir }}/{{ email }}"

- name: export private key
  shell: echo "{{ passphrase }}" | gpg --pinentry-mode loopback --batch --yes --passphrase-fd 0 --export-secret-keys --armor "{{ email }}" > '<{{ email }}>.private.gpg-key'
  args:
    chdir: "{{ export_dir }}/{{ email }}"
