---

- name: import keys
  include_tasks: import.yml
  vars:
    public_key: "{{ item.public }}"
    private_key: "{{ item.private }}"
    passphrase: "{{ item.passphrase }}"
  when:
    - item.public is defined
    - item.private is defined
    - item.passphrase is defined
  no_log: "{{ hide_secrets }}"
  with_items: "{{ keys }}"

- name: import trusts
  shell: gpg --import-ownertrust "{{ item.path }}"
  no_log: "{{ hide_secrets }}"
  when:
    - item.path is defined
  with_items:
    - "{{ trusts }}" 
