---

- name: import private keys
  shell: echo "{{ item.passphrase }}" | gpg --pinentry-mode loopback --batch --yes --passphrase-fd 0 --import "{{ item.private }}"
  when:
    - item.private is defined
    - item.passphrase is defined
  no_log: "{{ hide_secrets }}"
  with_items: "{{ keys }}"

- name: import public keys
  shell: echo "{{ item.passphrase }}" | gpg --pinentry-mode loopback --batch --yes --passphrase-fd 0 --import "{{ item.public }}"
  when:
    - item.public is defined 
    - item.passphrase is defined
  no_log: "{{ hide_secrets }}"
  with_items: "{{ keys }}"

- name: import trusts
  shell: gpg --import-ownertrust "{{ item.path }}"
  no_log: "{{ hide_secrets }}"
  when:
    - item.path is defined
  with_items:
    - "{{ trusts }}" 
