---

- name: export | ensure export directory presence
  file:
    path: "{{ dir }}/{{ key['email'] }}"
    state: directory

- name: export | generate revocation certificate  # noqa 306
  shell: >-
    echo -e "y\n0\n\ny" > "{{ command_file }}" &&
    echo "{{ key['passphrase'] }}" | {{ gpg_command }} --command-file "{{ command_file }}" --gen-revoke {{ key['email'] }}
    > {{ key['email'] }}.revocation-certificate
  args:
    chdir: "{{ dir }}/{{ key['email'] }}"
    executable: bash
    creates: "{{ key['email'] }}.revocation-certificate"
  vars:
    command_file: /tmp/cmd
    gpg_command: "gpg --pinentry-mode loopback --passphrase-fd 0"

- name: export | key    # noqa 306
  shell: >-
    echo "{{ key['passphrase'] }}" | {{ gpg_command }} {{ item.key }} --armor {{ key['email'] }}
    > {{ key['email'] }}.{{ item.value }}
  args:
    chdir: "{{ dir }}/{{ key['email'] }}"
    creates: "{{ key['email'] }}.{{ item.value }}"
  vars:
    exported_files:
      --export: public.gpg-key
      --export-secret-keys: private.gpg-key
      --export-secret-subkeys: private.subkeys_only.gpg-key
    gpg_command: "gpg --pinentry-mode loopback --passphrase-fd 0 --batch --yes"
  loop: "{{ exported_files | dict2items }}"
