---

- name: ensure export directory presence
  file:
    path: "{{ dir }}/{{ key['email'] }}"
    state: directory

- name: generate revocation certificate
  shell: echo -e "y\n0\n\ny" > "{{ command_file }}" && echo "{{ key['passphrase'] }}" | gpg --pinentry-mode loopback --command-file "{{ command_file }}" --passphrase-fd 0 --gen-revoke {{ key['email'] }} > {{ key['email'] }}.revocation-certificate
  args:
    chdir: "{{ dir }}/{{ key['email'] }}"
    executable: bash
    creates: "{{ key['email'] }}.revocation-certificate"
  vars:
    command_file: /tmp/cmd

- name: export key
  shell: echo "{{ key['passphrase'] }}" | gpg --pinentry-mode loopback --batch --yes --passphrase-fd 0 {{ item.key }} --armor {{ key['email'] }} > {{ key['email'] }}.{{ item.value }}
  args:
    chdir: "{{ dir }}/{{ key['email'] }}"
    creates: "{{ key['email'] }}.{{ item.value }}"
  vars:
    exported_files:
      --export: public.gpg-key
      --export-secret-keys: private.gpg-key
      --export-secret-subkeys: private.subkeys_only.gpg-key
  loop: "{{ exported_files | dict2items }}"

