---

- name: export | keys
  when:
    - keys is defined
    - key['email'] is defined
    - key['passphrase'] is defined
  include_tasks: key.yml
  loop: "{{ gpg_export['keys'] }}"
  loop_control:
    loop_var: key
  vars:
    dir: "{{ gpg_export['dir'] }}"

- name: export | trust
  when: export_trust
  shell: "gpg --export-ownertrust > {{ gpg_export['dir'] }}/trust.gpg"
  args:
    creates: "{{ gpg_export['dir'] }}/trust.gpg"
